### ISSUE TITLE
banner max-height too small on mobile styles

### ISSUE THREAD

**Issue by beckymargraf** [p2pu/p2pu-discourse-theme#6]
![IMG_3326](https://user-images.githubusercontent.com/8740979/145239353-750f09a4-50d9-4358-a633-2a238c01357f.jpeg)

Text gets cropped and it's difficult to scroll within the space to see all of the information. Banner should display all content without hiding any in scroll/collapse

**Comment by dirkcuys** [comment]
cool, problem was that discourse stylesheets set the header height on mobile
